server {
    listen 80;
    listen [::]:80;
    server_name getsiaq.online www.getsiaq.online;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name getsiaq.online www.getsiaq.online;

    client_max_body_size 30M;

    ssl_certificate /etc/letsencrypt/live/getsiaq.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/getsiaq.online/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location /static/ {
        alias /var/www/getsiaq/staticfiles_build/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    location /media/ {
        alias /var/www/getsiaq/media/;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        include proxy_params;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://unix:/run/getsiaq.sock;
    }
}
